name: Docker Build
description: 'Builds images for all supported FHIR versions'

inputs:
  tag:
    description: 'The tag to apply to the images'
    required: true
  fhirSchemaVersion:
    description: 'The FHIR schema version to package'
    required: true
  assemblyVersion:
    description: 'The assembly version to use'
    required: true
  composeLocation:
    description: 'The location of the docker-compose file'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build and Push Docker Images
      shell: bash
      run: |
        echo "Building and pushing Docker images for FHIR schema version ${{inputs.fhirSchemaVersion}}"
        docker-compose -f ${{inputs.composeLocation}} build -p ${{inputs.fhirSchemaVersion}} --build-arg FHIR_VERSION=${{inputs.fhirSchemaVersion}} --build-arg ASSEMBLY_VER=${{inputs.assemblyVersion}}
