name: update-semver
description: 'Update the build number with the SemVer from GitVersion'
inputs:
  configFilePath:
    description: 'Path to the GitVersion configuration file'
    required: false
    default: './GitVersion.yml'
outputs:
  informationalVersion: ${{ steps.SetVariablesFromGitVersion.outputs.informationalVersion }}
  majorMinorPatch: ${{ steps.SetVariablesFromGitVersion.outputs.majorMinorPatch }}
  nuGetVersion: ${{ steps.SetVariablesFromGitVersion.outputs.nuGetVersion }}
  assemblySemVer: ${{ steps.SetVariablesFromGitVersion.outputs.assemblySemVer }}
  assemblySemFileVer: ${{ steps.SetVariablesFromGitVersion.outputs.assemblySemFileVer }}
  semVer: ${{ steps.SetVariablesFromGitVersion.outputs.semVer }}
  buildNumber: ${{ steps.SetVariablesFromGitVersion.outputs.semVer }}
  buildVersion: ${{ steps.SetVariablesFromGitVersion.outputs.semVer }}
  buildVersionName: ${{ steps.SetVariablesFromGitVersion.outputs.semVer }}
  buildVersionNameWithBranch: ${{ steps.SetVariablesFromGitVersion.outputs.semVer }}
runs:
  using: 'composite'
  steps:
    
    - name: Install GitVersion'
      uses: gittools/actions/gitversion/setup@0.13.4

    - name: SetVariablesFromGitVersion
      id: -p:Version
      uses: gittools/actions/gitversion/execute@0.13.4
      with:
        configFilePath: './GitVersion.yml'
        targetFilePath: ${{github.workspace}}
        useConfigFile: true
