name: update-semver
description: 'Update the build number with the SemVer from GitVersion'
inputs:
  configFilePath:
    description: 'Path to the GitVersion configuration file'
    required: false
    default: './GitVersion.yml'
runs:
  using: 'composite'
  steps:
    
    - name: Install GitVersion'
      uses: gittools/actions/gitversion/setup@0.13.4

    - name: SetVariablesFromGitVersion
      id: version
      uses: gittools/actions/gitversion/execute@0.13.4
      with:
        configFilePath: ${{inputs.configFilePath}}
        targetFilePath: ${{github.workspace}}
        useConfigFile: true
