version: '3'

services:

  fhir:
    build: 
      context: ../../
      dockerfile: .devcontainer/Dockerfile
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock 
      - ../..:/workspace:cached

    entrypoint: /usr/local/share/docker-init.sh

    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    network_mode: "host"

    # so the container won't exit
    command: sleep infinity