# DESCRIPTION: 	
# Builds, tests, and packages the solution for the main branch.	

run-name: ${{github.ref_name}}-$(Date:yyyyMMdd)$(Rev:-r)
on: 
  workflow_dispatch

permissions:
   id-token: write
   contents: read
jobs:
  update-version:
    name: Determine Semver
    runs-on: ubuntu-latest
    steps:
      - name: Update Semver
        uses: ./.github/actions/update-semver.yml
