# DESCRIPTION: 	
# Builds, tests, and packages the solution for the main branch.	

run-name: ${{github.ref_name}}-${{github.run_id}}
on: 
  pull_request

permissions:
   id-token: write
   contents: read
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Latest .Net SDK
        uses: actions/setup-dotnet@v4

      - name: Install Older .Net SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
  update-version:
    name: Determine Semver
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Update Semver
        id: semver
        uses: ./.github/actions/update-semver
