# DESCRIPTION: 	
# Builds, tests, and packages the solution for the main branch.	

run-name: ${{github.ref_name}}-$(Date:yyyyMMdd)$(Rev:-r)
on: 
  pull_request

permissions:
   id-token: write
   contents: read
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.ref}}
  update-version:
    name: Determine Semver
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Update Semver
        uses: ./.github/actions/update-semver.yml
