# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

on: 
  pull_request

jobs:
  buildAndUnitTests:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      shell: bash
      run: dotnet build "./Microsoft.Health.Fhir.sln" --no-restore
      # run: dotnet build "./Microsoft.Health.Fhir.sln" --configuration ${{inputs.buildConfiguration}} "-p:ContinuousIntegrationBuild=true;AssemblyVersion=${{inputs.assemblyVersion}};FileVersion=${{inputs.fileVersion}};InformationalVersion=${{inputs.informationalVersion}};Version=${{inputs.majorMinorPatch}}" -warnaserror 
      
    - name: Test Azure.UnitTests
      run: dotnet test "Microsoft.Health.Fhir.sln" --no-build --filter "FullyQualifiedName~Azure.UnitTests" --verbosity normal
      #       run: dotnet test "Microsoft.Health.Fhir.sln" -p:ContinuousIntegrationBuild=true; --filter "FullyQualifiedName~Core.UnitTests" --configuration ${{inputs.buildConfiguration}} --no-build --verbosity normal

    - name: Test Core.UnitTests
      run: dotnet test "Microsoft.Health.Fhir.sln" --no-build --filter "FullyQualifiedName~Core.UnitTests" --verbosity normal

    - name: Test CosmosDb.UnitTests
      run: dotnet test "Microsoft.Health.Fhir.sln" --no-build --filter "FullyQualifiedName~CosmosDb.UnitTests" --verbosity normal

    - name: Test Api.UnitTests
      run: dotnet test "Microsoft.Health.Fhir.sln" --no-build --filter "FullyQualifiedName~Api.UnitTests" --verbosity normal

    - name: Test Web.UnitTests
      run: dotnet test "Microsoft.Health.Fhir.sln" --no-build --filter "FullyQualifiedName~Web.UnitTests" --verbosity normal

    - name: Test SchemaManager.UnitTests
      run: dotnet test "Microsoft.Health.Fhir.sln" --no-build --filter "FullyQualifiedName~SchemaManager.UnitTests" --verbosity normal

    - name: Test SqlServer.UnitTests
      run: dotnet test "Microsoft.Health.Fhir.sln" --no-build --filter "FullyQualifiedName~SqlServer.UnitTests" --verbosity normal

    - name: Test TaskManagement.UnitTests
      run: dotnet test "Microsoft.Health.Fhir.sln" --no-build --filter "FullyQualifiedName~TaskManagement.UnitTests" --verbosity normal
